# golangci-lint configuration  
# See https://golangci-lint.run/usage/configuration/

version: 2

linters:
  enable:
    - govet
    - misspell
    - ineffassign
    - staticcheck
    - unused
    - errcheck
    - gosec

run:
  timeout: 5m

linters-settings:
  goimports:
    local-prefixes: github.com/karpenter-provider-ibm-cloud

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
