linters:
  enable:
    - gofmt
    - govet
    - goimports
    - misspell
    - ineffassign
    - gosimple
    - staticcheck
    - unused
    - typecheck
    - errcheck
    - gosec

run:
  timeout: 5m

linters-settings:
  goimports:
    local-prefixes: github.com/karpenter-provider-ibm-cloud

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
