# Ko configuration for CI/CD (GitHub Actions)
# Uses pushed multi-arch base image with IBM Cloud CLI

baseImportPaths:
  github.com/pfeifferj/karpenter-provider-ibm-cloud/cmd/controller: ghcr.io/pfeifferj/karpenter-provider-ibm-cloud/base:latest

defaultPlatforms:
  - linux/amd64
  - linux/arm64

env:
  - CGO_ENABLED=0