apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodepools.karpenter.ibm.sh
spec:
  group: karpenter.ibm.sh
  names:
    kind: NodePool
    listKind: NodePoolList
    plural: nodepools
    singular: nodepool
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .spec.template.spec.nodeClassRef.name
          name: NodeClass
          type: string
        - jsonPath: .status.resources.nodes
          name: Nodes
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      schema:
        openAPIV3Schema:
          description: NodePool is the Schema for the NodePools API
          type: object
          required:
            - spec
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              description: NodePoolSpec defines the desired state of NodePool
              type: object
              required:
                - template
              properties:
                template:
                  description: Template contains the template for node creation
                  type: object
                  required:
                    - spec
                  properties:
                    metadata:
                      type: object
                    spec:
                      type: object
                      required:
                        - nodeClassRef
                        - requirements
                        - resources
                      properties:
                        nodeClassRef:
                          type: object
                          required:
                            - name
                            - kind
                            - apiGroup
                          properties:
                            name:
                              type: string
                            kind:
                              type: string
                            apiGroup:
                              type: string
                        requirements:
                          type: array
                          items:
                            type: object
                            required:
                              - key
                              - operator
                            properties:
                              key:
                                type: string
                              operator:
                                type: string
                                enum:
                                  - In
                                  - NotIn
                                  - Exists
                                  - DoesNotExist
                                  - Gt
                                  - Lt
                              values:
                                type: array
                                items:
                                  type: string
                              minValues:
                                type: integer
                                format: int32
                        resources:
                          type: object
                          required:
                            - requests
                          properties:
                            requests:
                              type: object
                              additionalProperties:
                                anyOf:
                                  - type: integer
                                  - type: string
                                pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                                x-kubernetes-int-or-string: true
                        taints:
                          type: array
                          items:
                            type: object
                            required:
                              - key
                              - effect
                            properties:
                              key:
                                type: string
                              value:
                                type: string
                              effect:
                                type: string
                disruption:
                  type: object
                  properties:
                    consolidateAfter:
                      type: string
                      pattern: ^(([0-9]+(s|m|h))+)|(Never)$
                    consolidationPolicy:
                      type: string
                      enum:
                        - WhenEmpty
                        - WhenEmptyOrUnderutilized
                    budgets:
                      type: array
                      items:
                        type: object
                        required:
                          - nodes
                        properties:
                          nodes:
                            type: string
                limits:
                  type: object
                  additionalProperties:
                    anyOf:
                      - type: integer
                      - type: string
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                weight:
                  type: integer
                  format: int32
                  minimum: 1
                  maximum: 100
            status:
              description: NodePoolStatus defines the observed state of NodePool
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                resources:
                  type: object
                  additionalProperties:
                    anyOf:
                      - type: integer
                      - type: string
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
      subresources:
        status: {}
