apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodeclaims.karpenter.ibm.sh
spec:
  group: karpenter.ibm.sh
  names:
    kind: NodeClaim
    listKind: NodeClaimList
    plural: nodeclaims
    singular: nodeclaim
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .spec.nodeClassRef.name
          name: Class
          type: string
        - jsonPath: .status.providerID
          name: ProviderID
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      schema:
        openAPIV3Schema:
          description: NodeClaim is the Schema for the NodeClaims API
          type: object
          required:
            - spec
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              description: NodeClaimSpec defines the desired state of NodeClaim
              type: object
              required:
                - nodeClassRef
                - requirements
                - resources
              properties:
                nodeClassRef:
                  description: NodeClassRef is a reference to the NodeClass that should be used
                  type: object
                  required:
                    - name
                    - kind
                    - apiGroup
                  properties:
                    name:
                      type: string
                    kind:
                      type: string
                    apiGroup:
                      type: string
                requirements:
                  description: Requirements specify the requirements that the node must satisfy
                  type: array
                  items:
                    type: object
                    required:
                      - key
                      - operator
                    properties:
                      key:
                        type: string
                      operator:
                        type: string
                        enum:
                          - In
                          - NotIn
                          - Exists
                          - DoesNotExist
                          - Gt
                          - Lt
                      values:
                        type: array
                        items:
                          type: string
                      minValues:
                        type: integer
                        format: int32
                resources:
                  description: Resources specify the resources that the node must have
                  type: object
                  required:
                    - requests
                  properties:
                    requests:
                      type: object
                      additionalProperties:
                        anyOf:
                          - type: integer
                          - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                taints:
                  description: Taints to be applied to the node
                  type: array
                  items:
                    type: object
                    required:
                      - key
                      - effect
                    properties:
                      key:
                        type: string
                      value:
                        type: string
                      effect:
                        type: string
            status:
              description: NodeClaimStatus defines the observed state of NodeClaim
              type: object
              properties:
                providerID:
                  description: ProviderID uniquely identifies the node in the cluster
                  type: string
                imageID:
                  description: ImageID is the ID of the image used by the node
                  type: string
                capacity:
                  description: Capacity represents the total resources of a node
                  type: object
                  additionalProperties:
                    anyOf:
                      - type: integer
                      - type: string
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                allocatable:
                  description: Allocatable represents the resources that are available for scheduling
                  type: object
                  additionalProperties:
                    anyOf:
                      - type: integer
                      - type: string
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                conditions:
                  description: Conditions is a list of conditions and their status
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
      subresources:
        status: {}
