{{- if .Values.additionalCAs.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karpenter.fullname" . }}-additional-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
type: Opaque
{{- $caBundle := "" }}
{{- range $filename := keys .Values.additionalCAs.certs | sortAlpha }}
{{- $caBundle = printf "%s%s" $caBundle (index $.Values.additionalCAs.certs $filename) }}
{{- if not (hasSuffix "\n" (index $.Values.additionalCAs.certs $filename)) }}
{{- $caBundle = printf "%s\n" $caBundle }}
{{- end }}
{{- end }}
data:
  ca_crt: {{ $caBundle | b64enc | quote }}
{{- end }}
