apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "karpenter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "karpenter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "karpenter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "karpenter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}{{ if .Values.image.digest }}@{{ .Values.image.digest }}{{ end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KARPENTER_LOG_LEVEL
              value: {{ .Values.logLevel | default "debug" | quote }}
            - name: KARPENTER_VERBOSE_LOG_LEVEL
              value: {{ .Values.verboseLogLevel | default "5" | quote }}
            - name: KARPENTER_DEBUG
              value: {{ .Values.debug | default "true" | quote }}
            - name: IBM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "karpenter.fullname" . }}-credentials
                  key: ibm_api_key
            - name: IBM_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ include "karpenter.fullname" . }}-credentials
                  key: region
            - name: VPC_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "karpenter.fullname" . }}-credentials
                  key: vpc_url
            - name: VPC_AUTH_TYPE
              valueFrom:
                secretKeyRef:
                  name: {{ include "karpenter.fullname" . }}-credentials
                  key: vpc_auth_type
            - name: VPC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "karpenter.fullname" . }}-credentials
                  key: vpc_api_key
            - name: CONTROLLER_MANAGER_VERBOSITY
              value: {{ .Values.controllerVerbosity | default "4" | quote }}
            - name: CONTROLLER_MANAGER_LOG_LEVEL
              value: {{ .Values.controllerLogLevel | default "debug" | quote }}
          ports:
            - name: metrics
              containerPort: {{ .Values.controller.metrics.port }}
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          {{- with .Values.controller.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.controller.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
