apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karpenter.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
type: Opaque
data:
  IBM_API_KEY: {{ required "IBM Cloud API Key is required" .Values.credentials.ibmApiKey | b64enc | quote }}
  IBM_REGION: {{ required "IBM Cloud Region is required" .Values.credentials.region | b64enc | quote }}
  VPC_URL: {{ .Values.credentials.vpcUrl | default "https://us-south.iaas.cloud.ibm.com/v1" | b64enc | quote }}
  VPC_AUTH_TYPE: {{ .Values.credentials.vpcAuthType | default "iam" | b64enc | quote }}
  VPC_APIKEY: {{ required "VPC API Key is required" .Values.credentials.vpcApiKey | b64enc | quote }}
