apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karpenter.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
type: Opaque
data:
  ibm_api_key: {{ required "IBM Cloud API Key is required" .Values.credentials.ibm_api_key | b64enc | quote }}
  vpc_apikey: {{ required "VPC API Key is required" .Values.credentials.vpc_apikey | b64enc | quote }}
  region: {{ required "IBM Cloud Region is required" .Values.credentials.region | b64enc | quote }}
  vpc_url: {{ .Values.credentials.vpc_url | default (printf "https://%s.iaas.cloud.ibm.com/v1" .Values.credentials.region) | b64enc | quote }}
  vpc_auth_type: {{ .Values.credentials.vpc_auth_type | default "iam" | b64enc | quote }}
