apiVersion: v2
name: karpenter-ibm
description: A Helm chart for Karpenter's IBM Cloud Provider with configurable Custom Resources, IKS/VPC mode support, and multiple NodePool management.
type: application
version: 0.3.42
appVersion: 0.3.42
keywords:
  - cluster
  - node
  - scheduler
  - autoscaling
  - lifecycle
  - ibm
  - cloud
  - vpc
  - iks
  - nodepool
  - custom-resources
home: https://karpenter.sh/
icon: https://repository-images.githubusercontent.com/278480393/dab059c8-caa1-4b55-aaa7-3d30e47a5616
sources:
  - https://github.com/kubernetes-sigs/karpenter/
annotations:
  "helm.sh/resource-policy": keep
