# Default values for karpenter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/pfeifferj/karpenter-provider-ibm-cloud/controller
  tag: latest
  pullPolicy: IfNotPresent
  digest: "sha256:98e1441aa5d15f6e23e58a466c2526942e853d49281eefffa64e22361f7a19ad"
  # Overrides the image tag whose default is the chart appVersion.

# Logging configuration
logLevel: "debug"           # Options: debug, info, warn, error
verboseLogLevel: "5"        # Verbosity level (1-5)
debug: "true"               # Enable debug mode
controllerVerbosity: "4"    # Controller manager verbosity (0-5)
controllerLogLevel: "debug" # Controller manager log level

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Pod Disruption Budget configuration
podDisruptionBudget:
  # The name of the PDB. If not set, it will use the release name
  name: ""
  # Maximum number of pods that can be unavailable
  maxUnavailable: 1

# IBM Cloud credentials configuration
credentials:
  # Required: ibm cloud api key for general operations
  ibm_api_key: ""
  # Required: ibm cloud region (e.g., us-south, eu-de)
  region: ""
  # Optional: vpc api endpoint url
  # If not provided, defaults to https://{region}.iaas.cloud.ibm.com/v1
  vpc_url: ""
  # Optional: vpc authentication type
  vpc_auth_type: "iam"
  # Required: vpc api key for vpc operations
  vpc_api_key: ""

# Controller configuration
controller:
  metrics:
    port: 8080
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8081
    initialDelaySeconds: 5
    timeoutSeconds: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: 8081
    initialDelaySeconds: 5
    timeoutSeconds: 1

# Metrics configuration
metrics:
  # Enable ServiceMonitor creation
  serviceMonitor:
    enabled: false
    additionalLabels: {}
    endpointConfig: {}
