# Default values for karpenter-ibm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Self-contained chart includes base Karpenter CRDs and IBM provider

replicaCount: 1

image:
  repository: ghcr.io/pfeifferj/karpenter-provider-ibm-cloud/controller
  tag: latest
  pullPolicy: IfNotPresent
  digest: "sha256:98e1441aa5d15f6e23e58a466c2526942e853d49281eefffa64e22361f7a19ad"
  # Overrides the image tag whose default is the chart appVersion.

# Logging configuration
logLevel: "debug"           # Options: debug, info, warn, error
verboseLogLevel: "5"        # Verbosity level (1-5)
debug: "true"               # Enable debug mode
controllerVerbosity: "4"    # Controller manager verbosity (0-5)
controllerLogLevel: "debug" # Controller manager log level

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Pod Disruption Budget configuration
podDisruptionBudget:
  # The name of the PDB. If not set, it will use the release name
  name: ""
  # Maximum number of pods that can be unavailable
  maxUnavailable: 1

# IBM Cloud credentials configuration
credentials:
  # Required: ibm cloud api key for general operations
  ibm_api_key: ""
  # Required: ibm cloud region (e.g., us-south, eu-de)
  region: ""
  # Optional: vpc api endpoint url
  # If not provided, defaults to https://{region}.iaas.cloud.ibm.com/v1
  vpc_url: ""
  # Optional: vpc authentication type
  vpc_auth_type: "iam"
  # Required: vpc api key for vpc operations
  vpc_api_key: ""

# IKS cluster configuration (for IKS integration)
# Optional: IKS cluster ID for IKS API integration
iksClusterID: ""
# Optional: cluster name for identification
clusterName: ""
# Bootstrap mode: auto, cloud-init, or iks-api
bootstrapMode: "auto"

# Controller configuration
controller:
  metrics:
    port: 8080
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8081
    initialDelaySeconds: 5
    timeoutSeconds: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: 8081
    initialDelaySeconds: 5
    timeoutSeconds: 1

# Metrics configuration
metrics:
  # Enable ServiceMonitor creation for Prometheus scraping
  serviceMonitor:
    enabled: false
    additionalLabels: {}
    # Scraping interval for metrics collection
    interval: 30s
    # Timeout for each scrape
    scrapeTimeout: 10s
    # Relabeling configuration for the ServiceMonitor
    relabelings: []
    # Metric relabeling configuration for the ServiceMonitor
    metricRelabelings: []
    # Additional endpoint configuration
    endpointConfig: {}
  
  # Enable PrometheusRule creation for alerting
  prometheusRule:
    enabled: false
    additionalLabels: {}
    # Rule evaluation interval
    interval: 30s
    # URL for runbook documentation
    runbookUrl: "https://github.com/pfeifferj/karpenter-provider-ibm-cloud/blob/main/docs/troubleshooting.md"
    
    # Alert configuration with customizable thresholds and timing
    alerts:
      # Controller availability alerts
      controllerDown:
        for: 5m
        severity: critical
      
      # Error rate alerts
      highErrorRate:
        threshold: 0.1  # 10% error rate
        for: 10m
        severity: warning
      
      # Performance alerts
      slowReconciliation:
        threshold: 60  # 60 seconds
        for: 15m
        severity: warning
        
      slowNodeProvisioning:
        threshold: 600  # 10 minutes
        for: 15m
        severity: warning
      
      # IBM Cloud API alerts
      apiErrors:
        threshold: 0.05  # 5% error rate
        for: 5m
        severity: warning
        
      apiRateLimit:
        threshold: 0.01  # 1% rate limit occurrence
        for: 2m
        severity: warning
      
      # Node provisioning alerts (CRITICAL - impacts workload scheduling)
      nodeProvisioningFailures:
        threshold: 0.01  # 1% failure rate
        for: 5m
        severity: critical
        
      noNodeProvisioning:
        podThreshold: 0  # Any unschedulable pods
        for: 10m
        severity: critical
      
      # Cache performance alerts
      lowCacheHitRate:
        threshold: 80  # 80% hit rate
        for: 30m
        severity: info
      
      # Resource utilization alerts
      highMemoryUsage:
        threshold: 500  # 500MB
        for: 30m
        severity: warning
        
      highCPUUsage:
        threshold: 80  # 80% CPU usage
        for: 30m
        severity: warning
    
    # Additional custom rule groups
    additionalRuleGroups: []
