apiVersion: karpenter.ibm.sh/v1alpha1
kind: IBMNodeClass
metadata:
  name: auto-placement
spec:
  region: us-south
  vpc: "123e4567-e89b-12d3-a456-426614174000"
  zone: us-south-1
  subnet: "123e4567-e89b-12d3-a456-426614174000"
  instanceRequirements:
    architecture: amd64
    minimumCPU: 2
    minimumMemory: 4
  placementStrategy:
    zoneBalance: Balanced
    subnetSelection:
      minimumAvailableIPs: 10
  image: ibm-ubuntu-24-04-6-minimal-amd64-2
