name: Package and Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod +x get_helm.sh
        ./get_helm.sh

    - name: Package Helm chart
      working-directory: charts
      run: |
        helm lint .  
        helm package . -d ../packaged-charts  

    - name: Generate Helm repo index
      run: |
        mkdir -p gh-pages
        mv packaged-charts/*.tgz gh-pages/
        helm repo index gh-pages --url https://pfeifferj.github.io/karpenter-provider-ibm-cloud

    - name: Deploy to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: gh-pages
        publish_branch: gh-pages
